FROM docker.io/node:12-stretch

WORKDIR '/web'

COPY package.json .

RUN npm install

COPY . .

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends chromium

ENV CHROME_BIN=chromium

CMD ["npm","run","start"]