FROM node:12.16.1

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

WORKDIR /web

ENV PATH /web/node_modules/.bin:$PATH

COPY package.json /web/package.json
RUN npm install
RUN npm install -g @angular/cli@9.1.1 --unsafe

COPY . /web

CMD ng serve --host 0.0.0.0